<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite0b52144c7e116466b62d4b14c56d09e
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Thedudeguy\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Thedudeguy\\' => 
        array (
            0 => __DIR__ . '/..' . '/thedudeguy/rcon/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite0b52144c7e116466b62d4b14c56d09e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite0b52144c7e116466b62d4b14c56d09e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
